name: kinorca_event
description: Kinorca event operator
version: 1.0.0
repository: https://github.com/kinorca/event-dart

environment:
  sdk: '>=2.16.2 <3.0.0'

dependencies:
  shelf: ^1.3.0
  shelf_router: ^1.1.2
  json_annotation: ^4.4.0
  http: ^0.13.4

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
  json_serializable: ^6.1.5
  build_runner: ^2.1.8
